name: CI

on:
  push:

jobs:
  tests:
    name: Run tests
    runs-on: ubuntu-latest

    permissions:
      contents: write

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Install Haskell
